version: '2'

services:

  orderer0:
    container_name: orderer0
    image: hyperledger/fabric-orderer
    dns_search: .
    volumes:
      - ./build/nodes/orderer:/etc/hyperledger/fabric
    ports:
      - 7050:7050

  peer0:
    container_name: peer0
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0:7051
      # - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/msp/signcerts/peer0Signer.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/msp/keystore/peer0Signer.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/msp/cacerts/peerOrg0.pem
      # - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peer/peer0/localMspConfig:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0
      # - couchdb0

#  couchdb1:
#    container_name: couchdb1
#    image: hyperledger/fabric-couchdb
##   Uncomment the port mapping if you want to expose the CouchDB service,
##   for example to utilize Fauxton User Interface in dev environments.
#    ports:
#      - "6984:5984"

  peer1:
    container_name: peer1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1:7051
    volumes:
        - ./build/nodes/peer1:/etc/hyperledger/fabric
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0

  peer2:
    container_name: peer2
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    volumes:
        - ./build/nodes/peer2:/etc/hyperledger/fabric
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer0
      - peer1

  peer3:
    container_name: peer3
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    volumes:
        - ./build/nodes/peer3:/etc/hyperledger/fabric
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer0
      - peer1

  peer4:
    container_name: peer4
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    volumes:
        - ./build/nodes/peer4:/etc/hyperledger/fabric
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer0
      - peer1
