version: '2'

services:

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer
    dns_search: .
    hostname: primary.orderer
    volumes:
      - ./build/nodes/orderer:/etc/hyperledger/fabric
    ports:
      - 7050:7050

  peer1:
    container_name: peer1
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1:7051
    volumes:
        - ./build/nodes/peer1.org1:/etc/hyperledger/fabric
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer

  peer2:
    container_name: peer2
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2
      - CORE_PEER_ADDRESS=peer2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    volumes:
        - ./build/nodes/peer2.org1:/etc/hyperledger/fabric
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer
      - peer1

  peer3:
    container_name: peer3
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3
      - CORE_PEER_ADDRESS=peer3:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    volumes:
        - ./build/nodes/peer3.org1:/etc/hyperledger/fabric
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer
      - peer1

  peer4:
    container_name: peer4
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4
      - CORE_PEER_ADDRESS=peer4:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org1:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    volumes:
        - ./build/nodes/peer4.org1:/etc/hyperledger/fabric
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer
      - peer1
