FROM hyperledger/fabric-baseimage:_BASE_TAG_
ENV PEER_CFG_PATH /etc/hyperledger/fabric
RUN mkdir -p /var/hyperledger/db $PEER_CFG_PATH
COPY bin/* /usr/local/bin
COPY config/*.yaml $PEER_CFG_PATH
CMD peer node start
