#!/bin/bash
#
# Copyright Greg Haskins All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

TLS=$1

url() {
    TYPE=$1
    NODE=$2
    PORT=$3

    if [ "$TLS" == "true" ]; then
        TYPE="$1s"
    fi

    echo $TYPE://$NODE:$PORT
}

http() {
    NODE=$1
    PORT=$2

    echo $(url "http" $NODE $PORT)
}

grpc() {
    NODE=$1
    PORT=$2

    echo $(url "grpc" $NODE $PORT)
}

peerurls() {
    for i in $(seq 1 4); do
        echo "$(url grpc peer$i, 7051)"
    done
}

includefile() {
    file=$1
    prefix=$2

    echo "|"

    while IFS= read -r line; do
        printf '%s%s\n' "$prefix" "$line"
    done < "$file"
}

generateconfig() {
    cat <<EOF
#
# Generated by fabric.git/examples/cluster.  DO NOT EDIT!
#
ca:
        url: $(http "ca" "7054")
        certificate: $(includefile ./build/nodes/ca/ca.crt "              ")

tlsca:
        url: $(http "tlsca" "7054")
        certificate: $(includefile ./build/nodes/tlsca/ca.crt "              ")

orderer:
        url:  $(grpc "orderer" "7050")
        hostname: orderer
        ca: $(includefile ./build/nodes/orderer/tls/ca.crt "              ")

peers:
$(for i in $(seq 1 4); do
      echo "       - api: $(grpc peer$i 7051)"
      echo "         events: $(grpc peer$i 7053)"
      echo "         hostname: peer$i"
done)

identity:
        principal: Admin@org1.net
        mspid: Org1MSP
        privatekey: $(includefile ./build/nodes/cli/tls/server.key  "              ")
        certificate: $(includefile ./build/nodes/cli/tls/server.crt  "              ")
EOF
}

cat <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: client-config
type: Opaque
data:
  client.config: $(generateconfig | base64)
EOF
